# ShieldCoreAI | Google Solution Challenge 2026
"""
DMCA Takedown Notice Generator using Gemini.
WHY: Detection without action is useless. This closes the loop.
Generates a legally structured DMCA notice ready to send to platform abuse teams.
"""

import json
import logging
import asyncio
from datetime import datetime
from config.settings import GEMINI_API_KEY

logger = logging.getLogger(__name__)

try:
    import google.generativeai as genai
    if GEMINI_API_KEY:
        genai.configure(api_key=GEMINI_API_KEY)
        _model = genai.GenerativeModel('gemini-1.5-flash')
    else:
        _model = None
except ImportError:
    _model = None

DMCA_FALLBACK = """DMCA TAKEDOWN NOTICE

Generated by ShieldCoreAI
Date: {date}

To Whom It May Concern,

I am the rights holder of the copyrighted content described below. I have a good faith belief that the content available at the URL specified below infringes upon my copyright.

Original Work: {asset_name}
Registered Owner: {owner_name}
Organization: {organization}
Registration Certificate ID: {cert_id}
SHA-256 Fingerprint: {sha256}

I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner or am authorized to act on behalf of the owner.

Signature: {owner_name}
Date: {date}
"""

async def generate_dmca_notice(violation: dict, asset: dict, language: str = 'en') -> dict:
    """
    Generate a complete DMCA takedown notice for a detected violation.
    Returns dict with: notice_text, platform_email, subject_line, sent_to_authority
    """
    date_str = datetime.utcnow().strftime('%B %d, %Y')

    if _model is None:
        text = DMCA_FALLBACK.format(
            date=date_str,
            asset_name=asset.get('asset_name', 'Unknown'),
            owner_name=asset.get('owner_name', 'Unknown'),
            organization=asset.get('organization', 'Unknown'),
            cert_id=asset.get('cert_id', 'N/A'),
            sha256=asset.get('sha256', 'N/A')
        )
        return {
            'notice_text': text,
            'platform_email': _guess_platform_email(violation.get('source_domain', '')),
            'subject_line': f'DMCA Takedown Notice - {asset.get("asset_name", "Copyrighted Content")}',
            'authority_urls': ['https://cybercrime.gov.in', 'https://copyright.gov.in'],
            'legal_basis': ['IT Act 2000', 'Copyright Act 1957'],
            'estimated_damage_inr': 0
        }

    lang_instruction = {
        'en': 'Write in English.',
        'hi': 'Write in Hindi (Devanagari script).',
        'ta': 'Write in Tamil.'
    }.get(language, 'Write in English.')

    prompt = f"""{lang_instruction}

    Generate a complete, formal DMCA Section 512(c) takedown notice. Use this data:

    Infringing URL: {violation.get('source_url', 'detected via manual scan')}
    Platform/Domain: {violation.get('source_domain', 'unknown platform')}
    Detection Method: {violation.get('detection_method', 'AI detection')}
    Detection Type: {violation.get('detection_type', 'theft')}
    Similarity Score: {violation.get('similarity_percent', 0)}%

    Original Asset: {asset.get('asset_name', 'Unknown')}
    Rights Holder: {asset.get('owner_name', 'Unknown')}
    Organization: {asset.get('organization', 'Unknown')}
    Certificate ID: {asset.get('cert_id', 'N/A')}
    SHA-256 Hash: {asset.get('sha256', 'N/A')}
    Sport Category: {asset.get('sport_category', 'Sports')}
    Registration Date: {asset.get('registered_at_unix', 'Unknown')}
    Estimated Rights Value: USD {asset.get('estimated_rights_value_usd', 250)}
    Date: {date_str}

    Respond ONLY with valid JSON (no markdown, no backticks):
    {{
      "notice_text": "complete formal DMCA notice letter text",
      "subject_line": "email subject line",
      "platform_email": "abuse email for this platform if known, else copyright@platform.com",
      "authority_urls": ["https://cybercrime.gov.in", "https://copyright.gov.in"],
      "legal_basis": ["IT Act 2000 Section 66C", "Copyright Act 1957 Section 51"],
      "estimated_damage_inr": number
    }}"""

    for attempt in range(2):
        try:
            loop = asyncio.get_event_loop()
            res = await loop.run_in_executor(None, lambda: _model.generate_content(prompt))
            txt = res.text.strip().strip('`')
            if txt.startswith('json\n'):
                txt = txt[5:]
            return json.loads(txt)
        except Exception as e:
            logger.warning(f'DMCA Gemini attempt {attempt + 1} failed: {e}')
            await asyncio.sleep(1)

    return {
        'notice_text': DMCA_FALLBACK.format(
            date=date_str, asset_name=asset.get('asset_name', ''),
            owner_name=asset.get('owner_name', ''), organization=asset.get('organization', ''),
            cert_id=asset.get('cert_id', ''), sha256=asset.get('sha256', '')
        ),
        'subject_line': f'DMCA Notice - {asset.get("asset_name", "")}',
        'platform_email': _guess_platform_email(violation.get('source_domain', '')),
        'authority_urls': ['https://cybercrime.gov.in'],
        'legal_basis': ['IT Act 2000', 'Copyright Act 1957'],
        'estimated_damage_inr': 0
    }


def _guess_platform_email(domain: str) -> str:
    """Return known abuse/copyright email for major platforms."""
    domain = domain.lower()
    platform_emails = {
        'youtube.com': 'copyright@youtube.com',
        'instagram.com': 'ip@instagram.com',
        'facebook.com': 'ip@fb.com',
        'twitter.com': 'copyright@twitter.com',
        'x.com': 'copyright@twitter.com',
        'tiktok.com': 'copyright@tiktok.com',
        'reddit.com': 'copyright@reddit.com',
        'twitch.tv': 'copyright@twitch.tv'
    }
    for k, v in platform_emails.items():
        if k in domain:
            return v
    return f'abuse@{domain}' if domain else 'abuse@platform.com'
