# SportShield AI | Google Solution Challenge 2026 | First Prize Target

import sendgrid
from sendgrid.helpers.mail import Mail
from config.settings import SENDGRID_API_KEY, SENDGRID_FROM_EMAIL
import logging

logger = logging.getLogger(__name__)

async def send_takedown_email(violation_dict: dict, recipient_email: str) -> dict:
    if not SENDGRID_API_KEY:
        return {'sent': False, 'reason': 'SendGrid not configured'}
        
    try:
        subject = f"DMCA Takedown Notice — {violation_dict.get('asset_name', 'Asset')}"
        html_content = f"""
        <h2>Notice of Copyright Infringement</h2>
        <p>This is a formal DMCA takedown notice generated by SportShield AI.</p>
        <p><strong>Asset:</strong> {violation_dict.get('asset_name')}</p>
        <p><strong>Owner:</strong> {violation_dict.get('owner_name')}</p>
        <p><strong>Evidence ID:</strong> {violation_dict.get('evidence_scan_id')}</p>
        <p>Please remove the unauthorized content immediately.</p>
        """
        
        message = Mail(
            from_email=SENDGRID_FROM_EMAIL or 'legal@sportshield.ai',
            to_emails=recipient_email,
            subject=subject,
            html_content=html_content
        )
        
        sg = sendgrid.SendGridAPIClient(api_key=SENDGRID_API_KEY)
        sg.send(message)
        
        return {'sent': True, 'reason': 'Email sent successfully'}
    except Exception as e:
        logger.error(f"SendGrid error: {e}")
        return {'sent': False, 'reason': str(e)[:100]}
