# SportShield AI | Google Solution Challenge 2026 | First Prize Target

"""4-page professional legal evidence PDF. ReportLab.
This is a MAJOR differentiator — no other team has legal-grade PDF."""

from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors

def generate_evidence_pdf(scan_result: dict, asset_data: dict = None) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    w, h = letter
    
    def footer(page):
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.gray)
        c.drawString(50, 30, f"SportShield AI Analysis Report | Cert ID: {scan_result.get('matched_cert_id', 'N/A')} | Page {page}")

    # PAGE 1
    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(colors.black)
    c.drawString(50, h - 70, "SPORTSHIELD AI")
    c.setFont("Helvetica", 14)
    c.drawString(50, h - 90, "DIGITAL RIGHTS EVIDENCE REPORT")
    c.setFont("Helvetica-Oblique", 12)
    c.drawString(50, h - 110, "GOOGLE SOLUTION CHALLENGE 2026")
    
    threat = scan_result.get('threat_level', 'UNKNOWN')
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.red if threat == "CRITICAL" else colors.orange if threat == "HIGH" else colors.black)
    c.drawString(50, h - 150, f"Threat Level: {threat}")
    c.setFillColor(colors.black)
    c.drawString(250, h - 150, f"Trust Score: {scan_result.get('trust_score', '')}")
    c.drawString(400, h - 150, f"Scan ID: {scan_result.get('scan_id', '')[:8]}")
    
    y = h - 200
    if scan_result.get('asset_match_found'):
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "UNAUTHORIZED CONTENT DETECTED")
        y -= 25; c.setFont("Helvetica", 12)
        c.drawString(50, y, f"Owner: {scan_result.get('matched_owner_name','')}")
        y -= 20; c.drawString(50, y, f"Organization: {scan_result.get('matched_organization','')}")
        y -= 20; c.drawString(50, y, f"Cert ID: {scan_result.get('matched_cert_id','')}")
        y -= 20; c.drawString(50, y, f"Similarity: {scan_result.get('similarity_percent','')} %")
        y -= 40
        
    if scan_result.get('deepfake_is_fake'):
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "DEEPFAKE DETECTED")
        y -= 25; c.setFont("Helvetica", 12)
        c.drawString(50, y, f"Confidence: {scan_result.get('deepfake_confidence','')} %")
        y -= 20; c.drawString(50, y, f"Verdict: {scan_result.get('deepfake_verdict','')}")
        y -= 20; c.drawString(50, y, f"Frames Analyzed: {scan_result.get('deepfake_frames_analyzed','')}")
        
    footer(1); c.showPage()

    # PAGE 2
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, h - 70, "EXIF FORENSIC ANALYSIS")
    y = h - 100; c.setFont("Helvetica", 12)
    c.drawString(50, y, f"Risk Score: {scan_result.get('exif_risk_score', '0')}")
    y -= 20; c.drawString(50, y, f"Flags: {', '.join(scan_result.get('exif_flags', []))}")
    
    y -= 40
    for k, v in scan_result.get('exif_data', {}).items():
        c.drawString(50, y, f"{k}: {v}")
        y -= 20
        
    y -= 40
    if scan_result.get('matched_original_url') and scan_result.get('scan_file_url'):
        c.drawString(50, y, "REGISTERED ORIGINAL vs SCANNED CONTENT")
        
    footer(2); c.showPage()
    
    # PAGE 3
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, h - 70, "LEGAL ACTION PLAN — Generated by Gemini 2.0 Flash")
    
    lr = scan_result.get('gemini_legal_report', {})
    y = h - 100; c.setFont("Helvetica", 12)
    from textwrap import wrap
    for txt in wrap(lr.get('summary', ''), 80):
        c.drawString(50, y, txt); y -= 15
        
    y -= 15; c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Immediate Actions:")
    y -= 15; c.setFont("Helvetica", 12)
    for act in lr.get('immediate_actions', []):
        for txt in wrap("- " + act, 80):
            c.drawString(60, y, txt); y -= 15
            
    y -= 15; c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Report To:")
    y -= 15; c.setFont("Helvetica", 12)
    for r in lr.get('report_to', []):
         c.drawString(60, y, f"{r.get('authority')} - ({r.get('url')})"); y -= 15

    footer(3); c.showPage()
    
    # PAGE 4
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, h - 70, "TECHNICAL EVIDENCE — FORENSIC RECORD")
    y = h - 100; c.setFont("Helvetica", 10)
    c.drawString(50, y, f"pHash: {scan_result.get('phash', '')}"); y -= 15
    c.drawString(50, y, f"dHash: {scan_result.get('dhash', '')}"); y -= 15
    c.drawString(50, y, f"aHash: {scan_result.get('ahash', '')}"); y -= 15
    c.drawString(50, y, f"SHA256: {scan_result.get('sha256', '')}"); y -= 30
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Content DNA Breakdowns:"); y -= 15
    c.setFont("Helvetica", 10)
    for k, v in scan_result.get('content_dna_signals', {}).items():
         c.drawString(50, y, f"{k}: {v.get('score')} - {v.get('interpretation')}")
         y -= 15
         
    footer(4); c.showPage()
    
    c.save()
    return buf.getvalue()
